[variables]
NODE_VERSION = "18"
PORT = "8080"

[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.build]
cmds = [
  "npm ci",
  "npm run build:client"
]

[phases.start]
cmd = "node railway-deploy.js"
