[variables]
NODE_VERSION = "18"

[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmd = "npm install"

[phases.build]
cmds = [
  "npm run build:client || echo 'Client build failed but continuing'",
  "ls -la",
  "ls -la dist/ || echo 'No dist directory'"
]

[phases.start]
cmd = "node server.js"
